# Generated by Django 3.1.7 on 2021-03-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210327_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('korean', 'Korean'), ('spanish', 'Spanish'), ('chinese', 'Chinese')], max_length=20, null=True),
        ),
    ]
