# Generated by Django 3.1.7 on 2021-04-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='accuracy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='checkIn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(),
        ),
    ]
