# Generated by Django 3.1.7 on 2021-04-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210331_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='checkIn',
            new_name='check_in',
        ),
    ]
